{
 "title": "Flink-Queries",
 "time": { "from": "2020-06-29T14:07:14.566Z", "to": "2020-06-29T14:08:00.743Z" },
 "panels": [
  {
   "title": "Query 1 - Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_output_query_1_dayAvgThroughput",
     "legendFormat": "24 hours"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_output_query_1_weekAvgThroughput",
     "legendFormat": "7 days"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_output_query_1_monthAvgThroughput",
     "legendFormat": "30 days"
    }
   ]
  },
  {
   "title": "Query 1 - Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaProducer_request_latency_avg{job_name=\"Query_1\", operator_name=~\"(Sink:_output_query_1_dayorg_apache_flink_streaming_api_windowing_time).*\"}",
     "legendFormat": "24 hours"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaProducer_request_latency_avg{job_name=\"Query_1\", operator_name=~\"(Sink:_output_query_1_weekorg_apache_flink_streaming_api_windowing_time).*\"}",
     "legendFormat": "7 days"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaProducer_request_latency_avg{job_name=\"Query_1\", operator_name=~\"(Sink:_output_query_1_monthorg_apache_flink_streaming_api_windowing_time).*\"}",
     "legendFormat": "30 days"
    }
   ]
  },
  {
   "title": "Query 2 - Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaProducer_request_latency_avg{job_name=\"Query_2\", operator_name=~\"(Sink:_output_query_2_dayorg_apache_flink_streaming_api_windowing_time).*\"}",
     "legendFormat": "24 hours"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaProducer_request_latency_avg{job_name=\"Query_2\", operator_name=~\"(Sink:_output_query_2_weekorg_apache_flink_streaming_api_windowing_time).*\"}",
     "legendFormat": "7 days"
    }
   ]
  },
  {
   "title": "Query 2 - Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_output_query_2_dayAvgThroughput",
     "legendFormat": "24 hours"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_output_query_2_weekAvgThroughput",
     "legendFormat": "7 days"
    }
   ]
  }
 ]
}