FROM flink:1.10.0
# Graphite
#RUN cp /opt/flink/opt/flink-metrics-graphite-1.10.0.jar /opt/flink/lib/
# Prometheus
RUN cp /opt/flink/opt/flink-metrics-prometheus-1.10.0.jar /opt/flink/lib/
WORKDIR /opt/flink/bin